### ISSUE TITLE
Can't initialize PWM on pin

### ISSUE THREAD

**Issue by 23RoMax** [akgnah/rockpi-penta#5]
I'm failing to run fan.py on Ubuntu 20.04 LTS (GNU/Linux 4.4.154-112-rockchip-gfdb18c8bab17 aarch64)
```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import fan
  File "/usr/bin/rockpi-penta/fan.py", line 6, in <module>
    pin13 = mraa.Pwm(13)
  File "/usr/local/lib/python3.8/dist-packages/mraa.py", line 482, in __init__
    _mraa.Pwm_swiginit(self, _mraa.new_Pwm(pin, owner, chipid))
ValueError: Error initialising PWM on pin
```

I'm assuming I have to enable it first somehow, but the documentation is lacking any information. Please assist.

**Comment by 23RoMax** [comment]
The missing piece of information has been found under: https://wiki.radxa.com/Rockpi4/Debian

`Common Hardware Interfaces, I2C, PWM, SPI, UART, etc`
